import { doc, setDoc, getDocs, collection, serverTimestamp, increment } from 'firebase/firestore';
import { db } from '@/firebase';

const SESSIONS_COLLECTION = 'sessions';

export interface SessionMetrics {
  totalUniqueUsers: number;
  returningUsers: number;
  totalSessions: number;
}

/**
 * Registers a session for the user for the current date (YYYY-MM-DD).
 * Increments visitCount and updates lastSeenAt atomically.
 */
export async function registerSession(uid: string): Promise<void> {
  if (!uid) return;

  try {
    const today = new Date().toISOString().split('T')[0];
    const sessionId = `${uid}_${today}`;
    const sessionRef = doc(db, SESSIONS_COLLECTION, sessionId);

    await setDoc(
      sessionRef,
      {
        uid,
        date: today,
        lastSeenAt: serverTimestamp(),
        visitCount: increment(1),
      },
      { merge: true }
    );
  } catch (err) {
    // Silent fail so tracking never disrupts UX
    console.warn('Error registrando sesión de usuario:', err);
  }
}

/**
 * Fetches and calculates session analytics for the Admin Panel,
 * excluding sessions generated by administrator accounts.
 */
export async function getSessionMetrics(): Promise<SessionMetrics> {
  try {
    // 1. Fetch admin UIDs to exclude them from community statistics
    const adminsColRef = collection(db, 'admins');
    const adminsSnapshot = await getDocs(adminsColRef).catch((err) => {
      console.warn('No fue posible consultar la colección admins para filtrado:', err);
      return { docs: [] };
    });
    const adminUids = new Set(adminsSnapshot.docs.map((docSnap) => docSnap.id));

    // 2. Fetch all session documents
    const colRef = collection(db, SESSIONS_COLLECTION);
    const snapshot = await getDocs(colRef);

    const userDatesMap = new Map<string, Set<string>>();
    let validExternalSessionsCount = 0;

    snapshot.docs.forEach((docSnap) => {
      const data = docSnap.data();
      const uid = data.uid;
      const date = data.date;

      // Skip sessions belonging to an administrator
      if (uid && adminUids.has(uid)) {
        return;
      }

      if (uid && date) {
        validExternalSessionsCount += 1;
        if (!userDatesMap.has(uid)) {
          userDatesMap.set(uid, new Set());
        }
        userDatesMap.get(uid)!.add(date);
      }
    });

    const totalUniqueUsers = userDatesMap.size;
    let returningUsers = 0;

    userDatesMap.forEach((datesSet) => {
      if (datesSet.size > 1) {
        returningUsers += 1;
      }
    });

    return {
      totalUniqueUsers,
      returningUsers,
      totalSessions: validExternalSessionsCount,
    };
  } catch (err) {
    console.error('Error fetching session metrics in AdminPanel:', err);
    return {
      totalUniqueUsers: 0,
      returningUsers: 0,
      totalSessions: 0,
    };
  }
}
